---
- name: Download source
  get_url: url=http://download.redis.io/releases/redis-{{ redis.version }}.tar.gz dest=/tmp

- name: Unarchive
  unarchive: src=/tmp/redis-{{ redis.version }}.tar.gz dest=/tmp copy=no creates=/tmp/redis-{{ redis.version }}

- name: Make
  shell: make chdir=/tmp/redis-{{ redis.version }} creates=/tmp/redis-{{ redis.version }}/src/redis-server

#- name: Move binaries
#  shell: cp -f {{ item }} {{ local.bin }} chdir=/tmp/redis-{{ redis.version }}/src creates={{ local.bin }}/{{ item }}
#  with_items:
#    - redis-cli
#    - redis-server
#    - redis-benchmark

- name: Copy configure
  template: src=redis.conf.j2 dest=/etc/redis.conf
  template: src=redis.j2 dest=/etc/init.d/redis mode=755
  notify:
    - Restart redis

- name: Start
  shell: /etc/init.d/redis start creates=/var/run/redis.pid
