---
- name: install Development tools
  yum: name='@Development tools' state=present

- name: install tools
  yum: name={{ item }} state=present
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel

- name: user bashprofil
  template: src=bash_profile.j2 dest={{ user.vagrant.home }}.bash_profile owner={{ user.vagrant.username }} group={{ user.vagrant.groupname }} mode=0755

- name: user bashrc
  template: src=bashrc.j2 dest={{ user.vagrant.home }}/.bashrc owner={{ user.vagrant.username }} group={{ user.vagrant.groupname }} mode=0755

- name: copy id_rsa
  copy: src=~/.ssh/id_rsa dest={{ user.vagrant.home }}/.ssh/id_rsa
